ChanceDays2/Controllers/EditHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChanceDays2.Models;
using AutoMapper;

namespace ChanceDays2.Controllers
{
    public class EditHistoryController : Controller
    {
        private ProjectDBContext db = new ProjectDBContext();

        //
        // GET: /EditHistory/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RecentChanges(int projectid = 0)
        {
            Project currentProject = db.Projects.Find(projectid);
            List<ProjectVersion> recentVersions = db.ProjectVersions.Where(b => b.parentId.Equals(projectid)).OrderByDescending(b => b.EditedOn).Take(3).ToList();

            return PartialView("_RecentChanges", recentVersions);
        }

        public ActionResult ViewEditHistory(int projectid = 0)
        {
            Project currentProject = db.Projects.Find(projectid);
       
            return View(currentProject);
        }

        public ActionResult PaginatedViewHistory(int projectid = 0, int requestedPage = 1, int PageSize = 10)
        {
            double pageSize = (double)PageSize;
            List<ProjectVersion> results;

            results = db.ProjectVersions.Where(b => b.parentId.Equals(projectid)).OrderByDescending(b => b.EditedOn).ToList();

            int pageNumbers = (int)Math.Ceiling(results.Count() / pageSize);
            int skipSize = (requestedPage - 1) * (int)pageSize;

            results = results.Skip(skipSize).Take((int)pageSize).ToList();

            PaginatedEditHistory editHistory = new PaginatedEditHistory();
            editHistory.currentPage = requestedPage;
            editHistory.totalPages = pageNumbers;

            editHistory.results = results;
            editHistory.ParentId = projectid;

            return PartialView("_PaginatedEditHistory", editHistory);
        }

        public ActionResult SingleViewEdit(int projectversionId = 0)
        {
            ProjectVersion viewVersion = db.ProjectVersions.Find(projectversionId);

            return View(viewVersion);
        }

        public ActionResult RestoreVersion(int projectversionId = 0, string editorname = "default")
        {
            Mapper.CreateMap<ProjectVersion, ProjectVersion>().ForMember(x => x.ProjectVersionId, o => o.Ignore());
   
            ProjectVersion restoreVersion = db.ProjectVersions.Find(projectversionId);

            ProjectVersion newVersion = new ProjectVersion();
            newVersion = Mapper.Map<ProjectVersion, ProjectVersion>(restoreVersion);

            string text = editorname.Replace("/", "\\");
            newVersion.EditedBy = db.Users.Where(b => b.Username.Equals(text)).First();
            newVersion.EditedOn = DateTime.Now;
            newVersion.ChangeDescription = "restored project to old snapshot";

            Project project = db.Projects.Find(restoreVersion.parentId);
 

            db.ProjectVersions.Add(newVersion);
            project.CurrentVersion = newVersion;
            db.SaveChanges();

            TempData["SuccessMessage"] = "Successfully restored project to old version!";
            return RedirectToAction("Details", "Project", new { id = restoreVersion.parentId });
        }
    }
}

ChanceDays2/Views/EditHistory/SingleViewEdit.cshtml
@model ChanceDays2.Models.ProjectVersion

@{
    ViewBag.Title = "SingleViewEdit";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#restore").click(function (e) {
            var url = '@Url.Action("RestoreVersion", "EditHistory", new { projectversionId = Model.ProjectVersionId, editorname = User.Identity.Name })';
            window.location.href = url;
        });
    });
</script>

<h2>Review Edit</h2>

<div style="padding-bottom: 45px;" class="alert alert-warning">You're viewing a snapshot of this project's details from @Model.EditedOn.ToShortDateString(). If you would like to go back, click <a href="@Url.Action("ViewEditHistory", "Project", new { id = Model.parentId })" class="alert-link">here.</a><br />
    If you'd like to restore the project current state to this snapshot, use the restore button. <br />
    <button id="restore" class="btn btn-warning pull-right">Restore</button>
</div>

<div class="row">
    <div class="col-lg-8">
        <div class="well well-lg">
            <strong>@Model.ProjectName</strong> <br />
            <strong>ChanceDay:</strong> @Model.ChanceDay <br />
            <strong>Project Status:</strong> @Model.ProcessStatus <br />
            <strong>Feedback Status:</strong> @Model.FeedbackStatus <br />
            <hr />
            <strong>Problem Description:</strong> @Model.ProblemDescription <br />
            <strong>Proposed Solution:</strong> @Model.ProposedSolution <br />
            <strong>Project Scope:</strong> @Model.ProjectScope <br />
            <strong>Pitch URL:</strong> @Model.PitchUrl <br />
            <hr />
            <strong>Latest Change:</strong> @Model.ChangeDescription <br />
        </div>
    </div>
    <div class="col-lg-4">
        <div class="well">
            <strong>Changed By:</strong> @Model.EditedBy.FirstName @Model.EditedBy.LastName <br />
            <strong>Changed On:</strong> @Model.EditedOn.ToShortDateString() at @Model.EditedOn.ToShortTimeString() <br />
        </div>
        <div class="well">
            <strong>Idea Owner:</strong> @if (Model.Owner != null) { 
                                          <text>
                                                @Model.Owner.LastName, @Model.Owner.FirstName
                                          </text>   
                                         } <br />
            <strong>Team Lead:</strong> @if (Model.Lead != null) { 
                                          <text>
                                                @Model.Lead.LastName, @Model.Lead.FirstName
                                          </text>   
                                         } <br />
            <strong>Presenter:</strong> @if (Model.Presenter != null) { 
                                          <text>
                                                @Model.Presenter.LastName, @Model.Presenter.FirstName
                                          </text>   
                                         } <br />
        </div>
    </div>
</div>

ChanceDays2/Views/EditHistory/ViewEditHistory.cshtml
@model ChanceDays2.Models.Project

@{
    ViewBag.Title = "ViewEditHistory";
}

<script type="text/javascript">
    $(document).ready(function () {
        var count = parseInt('@Model.ProjectId');
        var url = '@Url.Action("PaginatedViewHistory", "EditHistory")';
        returnPaginatedEditHistory(count, url, 1, 10);

        var returnUrl = '@Url.Action("Details", "Project", new { id = Model.ProjectId })';
        $("#return").click(function () {
            window.location.href = returnUrl;
        });
    });
</script>

<h3>View Edit History</h3>

<div class="row">
    <div id="results" class="col-lg-8">

    </div>
    <div class="col-lg-4">
        <div class="well">
            <strong>Project Name:</strong> @Model.CurrentVersion.ProjectName <br />
            <strong>Created By:</strong> @Html.ActionLink(String.Format("{0} {1}", Model.CreatedBy.FirstName, Model.CreatedBy.LastName), "Details", new { controller = "User", id = Model.CreatedBy.UserId }) <br />
            <strong>Created On:</strong> @Model.CreatedOn.ToShortDateString() <br />
            <strong>Created At: </strong> @Model.CreatedOn.ToShortTimeString()
        </div>
        <div>
            <button id="return" class="btn btn-default pull-right" type="button">Return to Project</button>
        </div>
        <div id="waitImage" class="center" style="width: 133px; z-index: 1050;">
            <div class="progress progress-striped active">
                <div class="progress-bar" role="progressbar" style="width: 100%"></div>
            </div>
        </div>
    </div>
</div>

ChanceDays2/Views/EditHistory/_PaginatedEditHistory.cshtml
@model ChanceDays2.Models.PaginatedEditHistory

<link rel="stylesheet" href='@Url.Content("~/Content/collapsefix.css")' />

 <div class="row">
     <div class="col-lg-12">
        <div class="panel-group" id="accordion">
        @{
            int i = 0;
            foreach(var oldVersion in Model.results){
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#@("collapse_" + i)">
                                edited by @oldVersion.EditedBy.FirstName @oldVersion.EditedBy.LastName at @oldVersion.EditedOn.ToShortTimeString() on @oldVersion.EditedOn.ToShortDateString()
                            </a>
                            @if (i == 0 && Model.currentPage == 1)
                            {
                                <span class="pull-right badge">
                                    Current
                                </span>
                            }
                        </h4>
                    </div>
                    <div id="@("collapse_" + i)" class="panel-collapse collapse">
                        <div class="panel-body">
                            @oldVersion.ChangeDescription

                            <button id="@oldVersion.ProjectVersionId" class="btn btn-small btn-default pull-right">View More</button>
                        </div>
                    </div>
                </div>
                i++;
            }
        }
        </div>
        <div class="col-lg-12">
            @if (Model.totalPages > 1){
                <ul id="paginationBar" class="pagination pagination-lg ul-centered">
                @if (Model.currentPage == 1) {
                    <li class="disabled"><a href="#">&laquo;</a></li>
                } else {
                    <li class="previousPage"><a href="#">&laquo;</a></li>   
                }
                @for(int j = 1; j <= Model.totalPages; j++){
                        if (j == Model.currentPage){
                            <li class="active"><a href="#">@j</a></li>   
                        }else {
                            <li><a href="#">@j</a></li>   
                        }      
                }
                @if (Model.currentPage == Model.totalPages){
                    <li class="disabled"><a href="#">&raquo;</a></li>   
                } else {
                    <li class="nextPage"><a href="#">&raquo;</a></li>   
                }
                </ul>
            }
        </div>
    </div>
</div>

ChanceDays2/Views/EditHistory/_RecentChanges.cshtml
@model IEnumerable<ChanceDays2.Models.ProjectVersion>

<div>
    <ul class="list-group">

@{
    
    int i = 0;
    foreach(var pastVersion in Model){
        <a href='@Url.Action("ViewEditHistory", "EditHistory", new { projectid = pastVersion.parentId })' class="list-group-item">
            @if (i == 0)
            {
                <span class="badge">Latest</span>
            }
            <small>edit by @pastVersion.EditedBy.FirstName @pastVersion.EditedBy.LastName on @pastVersion.EditedOn.ToShortDateString()</small>
        </a>
        i++;
    }

}
    </ul>
</div>