ChanceDays2/Models/Feedback.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChanceDays2.Models
{
    public class Feedback
    {
        public virtual int FeedbackId { get; set; }
        public virtual Project owner { get; set; }
        public virtual string Comment { get; set; }
        public virtual User Poster { get; set; }
        public virtual DateTime insertDate { get; set; }
    }

    public class NewFeedback
    {
        public virtual int parentProject { get; set; }
        public virtual string poster { get; set; }
        public virtual string comment { get; set; }
    }
}

ChanceDays2/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChanceDays2.Models;
using AutoMapper;

namespace ChanceDays2.Controllers
{
    public class FeedbackController : Controller
    {
        private ProjectDBContext db = new ProjectDBContext();
        
        //
        // GET: /Feedback/

        public ActionResult Index()
        {
            return View(db.Feedbacks.ToList());
        }

        /*
         * 
         * Add Feedback
         * 
         */
        public ActionResult AddFeedback(int projectid = 0)
        {
            Mapper.CreateMap<ProjectVersion, ProjectView>();
            Mapper.CreateMap<Project, ProjectView>();

            Project project = db.Projects.Find(projectid);

            ProjectView feedbackProject = Mapper.Map<Project, ProjectView>(project);
            Mapper.Map(project.CurrentVersion, feedbackProject);

            return View(feedbackProject);
        }
        
        [HttpPost]
        public ActionResult AddFeedback(NewFeedback newFeedback)
        {
            Feedback feedback = new Feedback();
            feedback.Comment = newFeedback.comment;
            feedback.Poster = db.Users.Where(user => user.Username == newFeedback.poster).First();
            feedback.insertDate = DateTime.Now;

            feedback.owner = db.Projects.Find(newFeedback.parentProject);

            db.Feedbacks.Add(feedback);
            db.SaveChanges();

            TempData["SuccessMessage"] = "Feedback successfully added!";
            return RedirectToAction("ViewFeedback", new { projectid = newFeedback.parentProject });
        }
        

        //
        // GET: /Project/Feedback/projectid
        //
        // Updated to v2.0 w/ audit trails
        public ActionResult ViewFeedback(int projectid = 0)
        {
            Mapper.CreateMap<ProjectVersion, ProjectView>();
            Mapper.CreateMap<Project, ProjectView>();

            Project project = db.Projects.Find(projectid);

            ProjectView feedbackProject = Mapper.Map<Project, ProjectView>(project);
            Mapper.Map(project.CurrentVersion, feedbackProject);

            feedbackProject.Feedbacks = db.Feedbacks.Where(b => b.owner.ProjectId.Equals(projectid)).ToList();

            //takes the comment and turns it into markedup html
            var md = new MarkdownDeep.Markdown();
            md.ExtraMode = true;
            md.SafeMode = false;

            foreach (var feedback in feedbackProject.Feedbacks)
            {
                string MarkedUp = md.Transform(feedback.Comment);
                feedback.Comment = MarkedUp;
            }

            return View(feedbackProject);
        }

        //
        // GET: /Feedback/Details/5
        /*
        public ActionResult Details(int id = 0)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);


        }

        //
        // GET: /Feedback/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Feedback/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Feedbacks.Add(feedback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(feedback);
        }

        //
        // GET: /Feedback/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        //
        // POST: /Feedback/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feedback);
        }

        //
        // GET: /Feedback/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        //
        // POST: /Feedback/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            db.Feedbacks.Remove(feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }*/
    }
}

ChanceDays2/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChanceDays2.Models;
using AutoMapper;

namespace ChanceDays2.Controllers
{
    public class ProjectController : Controller
    {
        private ProjectDBContext db = new ProjectDBContext();

        //
        // GET: /Project/
        
        //updated to v2.0 with audit trail
        public ActionResult JoinTeam(int projectid = 1)
        {
            Mapper.CreateMap<ProjectVersion, ProjectView>();
            Mapper.CreateMap<Project, ProjectView>();

            ProjectVersion currentVersion = db.Projects.Find(projectid).CurrentVersion;
            Project projectDetails = db.Projects.Find(projectid);

            ProjectView newProjectView = Mapper.Map<ProjectVersion, ProjectView>(currentVersion);
            Mapper.Map(projectDetails, newProjectView);

            List<Membership> memberships = db.Memberships.Where(b => b.Project.ProjectId == projectid).ToList();
            List<User> users = new List<User>();
            foreach (var membership in memberships)
            {
                users.Add(membership.Member);
            }
            newProjectView.Members = users;

            //begin constructing all member view
            List<User> allUsers = db.Users.ToList();
            foreach (User member in newProjectView.Members)
            {
                allUsers.Remove(member);
            }

            if (newProjectView == null)
            {
                return HttpNotFound("No project found");
            }

            var tuple = new Tuple<ProjectView, List<User>>(newProjectView, allUsers);
            return View(tuple);
        }
        
        //updated to v2.0 with audit trail
        public ActionResult AddUserToTeam(int projectid = 0, int userid = 0, string editorname = "default")
        {
            Mapper.CreateMap<ProjectVersion, ProjectVersion>();

            Project selectedProject = db.Projects.Find(projectid);
            ProjectVersion currentVersion = selectedProject.CurrentVersion;
            ProjectVersion newVersion = Mapper.Map<ProjectVersion, ProjectVersion>(currentVersion);

            //Edit changeLog, changeTime, changedBy
            User addUser = db.Users.Find(userid);
            newVersion.EditedBy = db.Users.Where(b=> b.Username == editorname).First();
            newVersion.EditedOn = DateTime.Now;
            newVersion.ChangeDescription = "added user, " + addUser.FirstName + " " + addUser.LastName;

            //set project to point to new version
            selectedProject.CurrentVersion = newVersion;

            if (currentVersion == null || addUser == null)
            {
                return HttpNotFound("No project found");
            }

            Membership newMembership = new Membership();
            newMembership.Member = addUser;
            newMembership.Project = selectedProject;
            db.Memberships.Add(newMembership);
            db.SaveChanges();

            TempData["SuccessMessage"] = addUser.FirstName + " " + addUser.LastName + " was successfully added to the team!";
            return RedirectToAction("Details", new { id = projectid });
        }
        
        //Updated to version 2.0 w/ audit trail
        public ActionResult RemoveUser(int projectid = 1)
        {
            Mapper.CreateMap<ProjectVersion, ProjectView>();
            Mapper.CreateMap<Project, ProjectView>();

            ProjectVersion currentVersion = db.Projects.Find(projectid).CurrentVersion;
            Project projectDetails = db.Projects.Find(projectid);

            ProjectView newProjectView = Mapper.Map<ProjectVersion, ProjectView>(currentVersion);
            Mapper.Map(projectDetails, newProjectView);

            List<Membership> memberships = db.Memberships.Where(b => b.Project.ProjectId == projectid).ToList();
            List<User> users = new List<User>();
            foreach (var membership in memberships)
            {
                users.Add(membership.Member);
            }

            newProjectView.Members = users;

            if (currentVersion == null || projectDetails == null)
            {
                return HttpNotFound("No project or no users");
            }

            return View(newProjectView);
        }

        //Updated to version 2.0 w/ audit trail
        public ActionResult RemoveUserFromTeam(int projectid = 0, int userid = 0, string editorname = "default")
        {
            Mapper.CreateMap<ProjectVersion, ProjectVersion>();

            Project selectedProject = db.Projects.Find(projectid);
            ProjectVersion currentVersion = selectedProject.CurrentVersion;
            ProjectVersion newVersion = Mapper.Map<ProjectVersion, ProjectVersion>(currentVersion);

            //Edit changeLog, changeTime, changedBy
            User removeUser = db.Users.Find(userid);
            newVersion.EditedBy = db.Users.Where(b => b.Username == editorname).First();
            newVersion.EditedOn = DateTime.Now;
            newVersion.ChangeDescription = "removed user, " + removeUser.FirstName + " " + removeUser.LastName;

            selectedProject.CurrentVersion = newVersion;

            if (selectedProject == null || removeUser == null)
            {
                return HttpNotFound("No project or no users found");
            }

            Membership deleted = db.Memberships.Where(i => i.Project.ProjectId.Equals(projectid) && i.Member.UserId.Equals(userid)).First();
            db.Memberships.Remove(deleted);
            db.SaveChanges();

            TempData["SuccessMessage"] = removeUser.FirstName + " " + removeUser.LastName + " was successfully removed from the team!";
            return RedirectToAction("Details", new { id = projectid });
        }
        
        //Updated to v2.0 w/ audit trail
        public ActionResult Index()
        {
            return View();
        }
        
        //Updated to v2.0 w/ audit trail
        [HttpPost]
        public ActionResult SearchAll(string searchTerm, int requestedPage, int PageSize)
        {
            double pageSize = (double)PageSize;
            string userInput = string.Empty;
            List<Project> results;

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                userInput = searchTerm.ToLower().Trim();
                results = db.Projects.Where(b => b.CurrentVersion.ProjectName.ToLower().Contains(userInput)).ToList();
                results.AddRange(db.Projects.Where(b => b.CurrentVersion.ChanceDay.ToLower().Contains(userInput)).ToList());
                results = results.Distinct().ToList();
            }
            else
            {
                results = db.Projects.ToList();
            }

            int pageNumbers = (int) Math.Ceiling(results.Count() / pageSize);
            int skipSize = (requestedPage - 1) * (int) pageSize;

            results = results.Skip(skipSize).Take((int)pageSize).ToList();

            PaginatedProjectSearchResults finalResults = new PaginatedProjectSearchResults();
            finalResults.currentPage = requestedPage;
            finalResults.totalPages = pageNumbers;

            //Convert results to projectView
            Mapper.CreateMap<ProjectVersion, ProjectView>();
            Mapper.CreateMap<Project, ProjectView>();
            
            ProjectVersion loopVersion = new ProjectVersion();
            List<ProjectView> projectViewResults = new List<ProjectView>();
            ProjectView newProjectView = new ProjectView();
            foreach (var singleProject in results)
            {
                loopVersion = singleProject.CurrentVersion;
                newProjectView = Mapper.Map<ProjectVersion, ProjectView>(loopVersion);
                Mapper.Map(singleProject, newProjectView);
                projectViewResults.Add(newProjectView);
            }

            finalResults.projectResults = projectViewResults;

            return PartialView("_SearchAll", finalResults);
        }

        //
        // GET: /Project/Details/5
        //
        //Updated to v2.0 w/ audit trail
        public ActionResult Details(int id = 0)
        {
            Mapper.CreateMap<ProjectVersion, ProjectView>();
            Mapper.CreateMap<Project, ProjectView>();

            Project project = db.Projects.Find(id);
            ProjectVersion projectVersion = project.CurrentVersion;
            if (project == null)
            {
                return HttpNotFound();
            }

            ProjectView newProjectView = Mapper.Map<ProjectVersion, ProjectView>(projectVersion);
            Mapper.Map(project, newProjectView);

            List<Membership> memberships = db.Memberships.Where(b => b.Project.ProjectId == id).ToList();
            List<User> users = new List<User>();
            foreach (var membership in memberships)
            {
                users.Add(membership.Member);
            }
            newProjectView.Members = users;
            return View(newProjectView);
        }
        
        //
        // GET: /Project/Create
        //
        // Updated to v2.0 w/ audit trail
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Project/Create
        //
        // Updated to v2.0 w/ audit trail
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectCreateView newProjectInfo)
        {
            Mapper.CreateMap<ProjectCreateView, ProjectVersion>();

            if (ModelState.IsValid)
            {
                Project newProject = new Project();
                User editor = db.Users.Where(b => b.Username == newProjectInfo.creatorName).First();
                newProject.CreatedBy = editor;
                newProject.CreatedOn = DateTime.Now;

                ProjectVersion newVersion = Mapper.Map<ProjectCreateView, ProjectVersion>(newProjectInfo);

ChanceDays2/Views/Feedback/AddFeedback.cshtml
@model ChanceDays2.Models.ProjectView

@{
    ViewBag.Title = "AddFeedback";
}
        <link rel="stylesheet" type="text/css" href="~/Scripts/mdd_styles.css" />
<script type="text/javascript">
    $(document).ready(function () {
        var alertDiv = $("#noText");
        var url = '@Url.Action("AddFeedback", "Feedback")';
        $("#submitFeedback").click(function (e) {
            e.preventDefault();
            if ($("#comment").val() == "") {
                $(alertDiv).html('<div class="alert alert-danger verticalSpace"><button type="button" class="close" aria-hidden="true">&times;</button>Feedback must contain text!</div>');
                $(alertDiv).show('slow');
                $("#textInput").addClass("has-error");
                $(".close").click(function () {
                    $(alertDiv).hide('slow');
                    $("#textInput").removeClass("has-error");
                    $(alertDiv).html("");
                });
            } else {
                $("#submitFeedbackForm").submit();
            }
        });

        $("textarea.mdd_editor").MarkdownDeep({
            help_location: "/Scripts/mdd_help.htm",
            ExtraMode: true
        });

        $("#returnToFeedback").click(function (event) {
            event.preventDefault();
            window.location.href = '@Url.Action("ViewFeedback", "Feedback", new { projectid = Model.ProjectId })';
        });
    });
</script>

<div id="noText"></div>


@using (Html.BeginForm(null, null, FormMethod.Post,new { id = "submitFeedbackForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

<div class="row">
    <div class="col-lg-8">
        @Html.Hidden("parentProject", Model.ProjectId)
        @Html.Hidden("poster", Context.User.Identity.Name)
        <div id="textInput" class="form-group">
            <label for="comment">Comment:</label>
            <div class="mdd_toolbar"></div>
            <textarea class="mdd_editor form-control" id="comment" name="comment" rows="8"></textarea>
        </div>
        <div class="form-group">
            <div class="pull-right">
                <button id="returnToFeedback" class="btn btn-default">Return to Feedback</button>
                <button id="submitFeedback" class="btn btn-primary">Submit Feedback</button>
            </div>
        </div>
        <div class="well mdd_preview col-lg-12 verticalSpace2"></div>
    </div>

    <div class="col-lg-4">
        <div class="well">
            <strong>Chance Day:</strong> @Html.DisplayFor(ModelProject => Model.ChanceDay) <br />
            <strong>Project Name: </strong> @Html.DisplayFor(ModelProject => Model.ProjectName) <br />
            <strong>Pitch URL: </strong> @Html.DisplayFor(ModelProject => Model.PitchUrl) <br />
            <strong>Process Status: </strong> @Html.DisplayFor(ModelProject => Model.ProcessStatus) <br />
            <strong>Feedback Status: </strong> @Html.DisplayFor(ModelProject => Model.FeedbackStatus) <br />
        </div>
    </div>
</div>
    
}

ChanceDays2/Views/Feedback/Delete.cshtml
@model ChanceDays2.Models.Feedback

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Feedback</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ChanceDays2/Views/Feedback/Details.cshtml
@model ChanceDays2.Models.Feedback

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Feedback</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comment)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comment)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.FeedbackId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ChanceDays2/Views/Feedback/Edit.cshtml
@model ChanceDays2.Models.Feedback

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Feedback</legend>

        @Html.HiddenFor(model => model.FeedbackId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Comment)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChanceDays2/Views/Feedback/Index.cshtml
@model IEnumerable<ChanceDays2.Models.Feedback>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FeedbackId }) |
            @Html.ActionLink("Details", "Details", new { id=item.FeedbackId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.FeedbackId })
        </td>
    </tr>
}

</table>

ChanceDays2/Views/Feedback/ProjectFeedback.cshtml
@model IEnumerable<ChanceDays2.Models.Feedback>

@{
    ViewBag.Title = "ProjectFeedback";
}

<h2>ProjectFeedback</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FeedbackId }) |
            @Html.ActionLink("Details", "Details", new { id=item.FeedbackId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.FeedbackId })
        </td>
    </tr>
}

</table>

ChanceDays2/Views/Feedback/ViewFeedback.cshtml
@model ChanceDays2.Models.ProjectView

@{
    ViewBag.Title = "ViewFeedback";
}

<script type="text/javascript">
    $(document).ready(function () {
        var url = '@Url.Action("SearchAll", "Project")';

        $("#returnToProject").click(function (event) {
            window.location.href = '@Url.Action("Details", "Project", new { id = Model.ProjectId })';
        });

        $("#addFeedback").click(function (event) {
            window.location.href = '@Url.Action("AddFeedback", "Feedback", new {projectid = Model.ProjectId })';
        });

        $('.close').click(function () {
            $('.alert').hide('slow');
        });
    });
</script>

@if (TempData["SuccessMessage"] != null)
{
     <div class="alert alert-success verticalSpace2">
        <button type="button" class="close" aria-hidden="true">&times;</button>
         @TempData["SuccessMessage"]
    </div>
}

<h3>View Feedback</h3>

<div class="row">
    <div class="col-lg-8">
    @foreach (var feedback in Model.Feedbacks.Reverse())
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href='@Url.Action("Details", "User", new { id = feedback.Poster.UserId })'> @Html.DisplayFor(feedbackItem => feedback.Poster.FirstName) @Html.DisplayFor(feedbackItem => feedback.Poster.LastName)</a> at @Html.DisplayFor(feedbackItem => feedback.insertDate)
            </div>
            <div class="panel-body">
                @Html.Raw(feedback.Comment)
            </div>
        </div>
    }

    </div>
    <div class="col-lg-4">
        <div class="well">
            <strong>Chance Day:</strong> @Html.DisplayFor(ModelProject => Model.ChanceDay) <br />
            <strong>Project Name: </strong> @Html.DisplayFor(ModelProject => Model.ProjectName) <br />
            <strong>Pitch URL: </strong> @Html.DisplayFor(ModelProject => Model.PitchUrl) <br />
            <strong>Process Status: </strong> @Html.DisplayFor(ModelProject => Model.ProcessStatus) <br />
            <strong>Feedback Status: </strong> @Html.DisplayFor(ModelProject => Model.FeedbackStatus) <br />
        </div>
        <div class="pull-right">
            <button id="returnToProject" class="btn btn-default">Back To Project</button>
            <button id="addFeedback" class="btn btn-primary">Add Feedback</button>
        </div>
    </div>
</div>